package endpoint

import (
	"testing"
)

func TestGenerate(t *testing.T) {
	input := ServiceSpec{
		Name: "Service",
		Package: PackageSpec{
			Name: "todo",
			Path: "github.com/sagikazarmark/modern-go-application/internal/app/mga/todo",
		},
		Endpoints: []EndpointSpec{
			{
				Name: "Call",
			},
			{
				Name: "OtherCall",
			},
		},
	}

	res, err := Generate("github.com/sagikazarmark/modern-go-application/internal/app/mga/todo/todogen", input, true)
	if err != nil {
		t.Fatal(err)
	}

	expected := `// Code generated by mga tool. DO NOT EDIT.
package todogen

import (
	"github.com/go-kit/kit/endpoint"
	kitoc "github.com/go-kit/kit/tracing/opencensus"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
	"github.com/sagikazarmark/modern-go-application/internal/app/mga/todo"
)

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	Call      endpoint.Endpoint
	OtherCall endpoint.Endpoint
}

// MakeEndpoints returns an Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service todo.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Chain(middleware...)

	return Endpoints{
		Call:      mw(MakeCallEndpoint(service)),
		OtherCall: mw(MakeOtherCallEndpoint(service)),
	}
}

// TraceEndpoints returns an Endpoints struct where each endpoint is wrapped with a tracing middleware.
func TraceEndpoints(endpoints Endpoints) Endpoints {
	return Endpoints{
		Call:      kitoc.TraceEndpoint("todo.Call")(endpoints.Call),
		OtherCall: kitoc.TraceEndpoint("todo.OtherCall")(endpoints.OtherCall),
	}
}
`

	if res != expected {
		t.Error("the generated code does not match the expected one")
	}
}
