run:
    skip-files:
        # See https://github.com/mvdan/gofumpt/issues/142
        - internal/scaffold/service/test/service.go

linters-settings:
    gci:
        local-prefixes: sagikazarmark.dev/mga
    goimports:
        local-prefixes: sagikazarmark.dev/mga
    golint:
        min-confidence: 0

linters:
    presets:
        - bugs
        - unused
        - format
        - import
