issues:
    exclude-files:
        # See https://github.com/mvdan/gofumpt/issues/142
        - internal/scaffold/service/test/service.go

        - internal/generate/testify/mock/mockgen/test/service.go

linters-settings:
    gci:
        sections:
            - standard
            - default
            - prefix(sagikazarmark.dev/mga)
    goimports:
        local-prefixes: sagikazarmark.dev/mga

linters:
    presets:
        - bugs
        - unused
        - format
        - import
    disable:
        - depguard
        - musttag
        - gocheckcompilerdirectives
