// +build !ignore_autogenerated

// Copyright 2020 Acme Inc.
// All rights reserved.
//
// Licensed under "Only for testing purposes" license.

// Code generated by mga tool. DO NOT EDIT.

package pkgdriver

import (
	"context"
	"errors"
	"github.com/go-kit/kit/endpoint"
	kitoc "github.com/go-kit/kit/tracing/opencensus"
	kitxendpoint "github.com/sagikazarmark/kitx/endpoint"
	"sagikazarmark.dev/mga/internal/generate/kit/endpoint/testdata/generator/service_with_struct"
)

// endpointError identifies an error that should be returned as an error endpoint.
type endpointError interface {
	EndpointError() bool
}

// Endpoints collects all of the endpoints that compose the underlying service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	Call endpoint.Endpoint
}

// MakeEndpoints returns a(n) Endpoints struct where each endpoint invokes
// the corresponding method on the provided service.
func MakeEndpoints(service service_with_struct.Service, middleware ...endpoint.Middleware) Endpoints {
	mw := kitxendpoint.Combine(middleware...)

	return Endpoints{Call: kitxendpoint.OperationNameMiddleware("service_with_struct.Call")(mw(MakeCallEndpoint(service)))}
}

// TraceEndpoints returns a(n) Endpoints struct where each endpoint is wrapped with a tracing middleware.
func TraceEndpoints(endpoints Endpoints) Endpoints {
	return Endpoints{Call: kitoc.TraceEndpoint("service_with_struct.Call")(endpoints.Call)}
}

// CallRequest is a request struct for Call endpoint.
type CallRequest struct {
	Req service_with_struct.Request
}

// CallResponse is a response struct for Call endpoint.
type CallResponse struct {
	Response service_with_struct.Response
	Err      error
}

// MakeCallEndpoint returns an endpoint for the matching method of the underlying service.
func MakeCallEndpoint(service service_with_struct.Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(*CallRequest)

		response, err := service.Call(ctx, req.Req)

		if err != nil {
			if endpointErr := endpointError(nil); errors.As(err, &endpointErr) && endpointErr.EndpointError() {
				return &CallResponse{
					Err:      err,
					Response: response,
				}, err
			}

			return &CallResponse{
				Err:      err,
				Response: response,
			}, nil
		}

		return &CallResponse{Response: response}, nil
	}
}
